var datas = [
    {
        img: 'images/car/car1.jpg',
        link: 'https://www.toyota.com/',
        price: '$145.000',
        brand: 'Toyota',
        name: 'Supra 2022',
        comments: '943',
    },
    {
        img: 'images/car/car2.jpg',
        link: 'https://www.toyota.com/',
        price: '$545.000',
        brand: 'Toyota',
        name: 'Supra 1980',
        comments: '45673',
    },
    {
        img: 'images/car/car3.jpg',
        link: 'https://www.toyota.com/',
        price: '$175.000',
        brand: 'Toyota',
        name: 'Supra 2023',
        comments: '235',
    },
    {
        img: 'images/car/car1.jpg',
        link: 'https://www.toyota.com/',
        price: '$145.000',
        brand: 'Toyota',
        name: 'Supra 2022',
        comments: '943',
    },
    {
        img: 'images/car/car2.jpg',
        link: 'https://www.toyota.com/',
        price: '$545.000',
        brand: 'Toyota',
        name: 'Supra 1980',
        comments: '45673',
    },
    {
        img: 'images/car/car3.jpg',
        link: 'https://www.toyota.com/',
        price: '$175.000',
        brand: 'Toyota',
        name: 'Supra 2023',
        comments: '235',
    },
    {
        img: 'images/car/car1.jpg',
        link: 'https://www.toyota.com/',
        price: '$145.000',
        brand: 'Toyota',
        name: 'Supra 2022',
        comments: '943',
    },
    {
        img: 'images/car/car2.jpg',
        link: 'https://www.toyota.com/',
        price: '$545.000',
        brand: 'Toyota',
        name: 'Supra 1980',
        comments: '45673',
    },
    {
        img: 'images/car/car3.jpg',
        link: 'https://www.toyota.com/',
        price: '$175.000',
        brand: 'Toyota',
        name: 'Supra 2023',
        comments: '235',
    },
    {
        img: 'images/car/car1.jpg',
        link: 'https://www.toyota.com/',
        price: '$145.000',
        brand: 'Toyota',
        name: 'Supra 2022',
        comments: '943',
    },
    {
        img: 'images/car/car2.jpg',
        link: 'https://www.toyota.com/',
        price: '$545.000',
        brand: 'Toyota',
        name: 'Supra 1980',
        comments: '45673',
    },
    {
        img: 'images/car/car3.jpg',
        link: 'https://www.toyota.com/',
        price: '$175.000',
        brand: 'Toyota',
        name: 'Supra 2023',
        comments: '235',
    },
    {
        img: 'images/car/car1.jpg',
        link: 'https://www.toyota.com/',
        price: '$145.000',
        brand: 'Toyota',
        name: 'Supra 2022',
        comments: '943',
    },
    {
        img: 'images/car/car2.jpg',
        link: 'https://www.toyota.com/',
        price: '$545.000',
        brand: 'Toyota',
        name: 'Supra 1980',
        comments: '45673',
    },
    {
        img: 'images/car/car3.jpg',
        link: 'https://www.toyota.com/',
        price: '$175.000',
        brand: 'Toyota',
        name: 'Supra 2023',
        comments: '235',
    },
    {
        img: 'images/car/car1.jpg',
        link: 'https://www.toyota.com/',
        price: '$145.000',
        brand: 'Toyota',
        name: 'Supra 2022',
        comments: '943',
    },
    {
        img: 'images/car/car2.jpg',
        link: 'https://www.toyota.com/',
        price: '$545.000',
        brand: 'Toyota',
        name: 'Supra 1980',
        comments: '45673',
    },
    {
        img: 'images/car/car3.jpg',
        link: 'https://www.toyota.com/',
        price: '$175.000',
        brand: 'Toyota',
        name: 'Supra 2023',
        comments: '235',
    },
];


datas.forEach(element => {
    var html = `<div class="card"><div class="image-container"><img src="${element.img}" alt=""></div> <div class="text-container"><div class="name"><div class="brand"><a href="${element.link}" class="link">${element.brand}</a></div><div class="product-name">${element.name}</div></div><div class="stars">⭐️⭐️⭐️⭐️⭐️<span class="comments">(${element.comments})</span></div><div class="price">${element.price}</div></div></div >`;
    $('.cards').append(html);
});