var datas = [
    {
        img: 'images/motobike/motobike1.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$45.000',
        brand: 'Yamaha',
        name: 'R15M kjhfkh kwehfk lwkef lkwejfl kwlkej lwkejf ',
        comments: '1234',
    },
    {
        img: 'images/motobike/motobike2.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$55.000',
        brand: 'Yamaha',
        name: 'R3',
        comments: '874',
    },
    {
        img: 'images/motobike/motobike3.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$40.000',
        brand: 'Yamaha',
        name: 'R15',
        comments: '209',
    },
    {
        img: 'images/motobike/motobike4.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$37.000',
        brand: 'Yamaha',
        name: 'R9',
        comments: '672',
    },
    {
        img: 'images/motobike/motobike1.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$45.000',
        brand: 'Yamaha',
        name: 'R15M',
        comments: '987',
    },
    {
        img: 'images/motobike/motobike2.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$55.000',
        brand: 'Yamaha',
        name: 'R3',
        comments: '365',
    },
    {
        img: 'images/motobike/motobike3.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$40.000',
        brand: 'Yamaha',
        name: 'R15',
        comments: '621',
    },
    {
        img: 'images/motobike/motobike1.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$45.000',
        brand: 'Yamaha',
        name: 'R15M kjhfkh kwehfk lwkef lkwejfl kwlkej lwkejf ',
        comments: '1234',
    },
    {
        img: 'images/motobike/motobike2.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$55.000',
        brand: 'Yamaha',
        name: 'R3',
        comments: '874',
    },
    {
        img: 'images/motobike/motobike3.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$40.000',
        brand: 'Yamaha',
        name: 'R15',
        comments: '209',
    },
    {
        img: 'images/motobike/motobike4.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$37.000',
        brand: 'Yamaha',
        name: 'R9',
        comments: '672',
    },
    {
        img: 'images/motobike/motobike1.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$45.000',
        brand: 'Yamaha',
        name: 'R15M',
        comments: '987',
    },
    {
        img: 'images/motobike/motobike2.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$55.000',
        brand: 'Yamaha',
        name: 'R3',
        comments: '365',
    },
    {
        img: 'images/motobike/motobike3.jpg',
        link: 'https://www.yamaha-motor-india.com/',
        price: '$40.000',
        brand: 'Yamaha',
        name: 'R15',
        comments: '621',
    },
];


datas.forEach(element => {
    var html = `<div class="card"><div class="image-container"><img src="${element.img}" alt=""></div> <div class="text-container"><div class="name"><div class="brand"><a href="${element.link}" class="link">${element.brand}</a></div><div class="product-name">${element.name}</div></div><div class="stars">⭐️⭐️⭐️⭐️⭐️<span class="comments">(${element.comments})</span></div><div class="price">${element.price}</div></div></div >`;
    $('.cards').append(html);
});
